# Generated by Django 5.2.7 on 2026-01-20 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_itempedido_options_itempedido_atualizado_em_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='pedido',
            field=models.OneToOneField(blank=True, help_text='Pedido associado a este pagamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='orders.pedido'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que realizou o pagamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pix', 'Pix'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('boleto', 'Boleto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
