# Generated by Django 5.2.7 on 2026-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do usuário', max_length=20, null=True),
        ),
    ]
