# Generated by Django 5.2.7 on 2026-01-20 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['-total_vendas'], 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='contabancariaartista',
            options={'verbose_name': 'Conta Bancária do Artista', 'verbose_name_plural': 'Contas Bancárias dos Artistas'},
        ),
        migrations.AddField(
            model_name='artista',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Avaliação média (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='artista',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente Aprovação'), ('aprovado', 'Aprovado'), ('bloqueado', 'Bloqueado')], default='pendente', help_text='Status de aprovação da plataforma', max_length=20),
        ),
        migrations.AddField(
            model_name='artista',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='artista',
            name='total_pedidos',
            field=models.PositiveIntegerField(default=0, help_text='Total de pedidos processados', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='artista',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0, help_text='Total de itens vendidos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contabancariaartista',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contabancariaartista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
