# Generated by Django 5.2.7 on 2026-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('uv', 'Impressora UV'), ('sublimacao', 'Sublimação'), ('serigrafia', 'Serigrafia'), ('digital', 'Digital')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'ordering': ['nome'],
            },
        ),
    ]
