# Generated by Django 5.2.10 on 2026-01-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impressora',
            options={'ordering': ['nome'], 'verbose_name': ('Impressora', 'Impressoras')},
        ),
        migrations.AlterField(
            model_name='impressora',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='localizacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='tipo',
            field=models.CharField(choices=[('uv', 'Impressora UV'), ('sublimacao', 'Sublimação'), ('serigrafia', 'Serigrafia'), ('digital', 'Digital')], max_length=50),
        ),
    ]
