# Generated by Django 5.2.7 on 2026-01-20 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_itempedido_options_itempedido_atualizado_em_and_more'),
        ('printing', '0002_alter_impressora_options_alter_impressora_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impressora',
            options={'ordering': ['nome'], 'verbose_name': 'Impressora', 'verbose_name_plural': 'Impressoras'},
        ),
        migrations.CreateModel(
            name='FilaImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('imprimindo', 'Imprimindo'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Ordem de prioridade na fila (menor = mais prioritário)', validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Notas sobre a impressão')),
                ('impressora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas', to='printing.impressora')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fila_impressao', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Fila de Impressão',
                'verbose_name_plural': 'Filas de Impressão',
                'ordering': ['-prioridade', 'criado_em'],
                'indexes': [models.Index(fields=['status', 'prioridade'], name='printing_fi_status_a5a467_idx'), models.Index(fields=['criado_em'], name='printing_fi_criado__279abd_idx')],
            },
        ),
    ]
