# Generated by Django 5.2.7 on 2026-01-20 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_itempedido_options_itempedido_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
