# Generated by Django 5.2.7 on 2026-01-20 17:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('categoria', models.CharField(choices=[('compras', 'Compras'), ('criacao', 'Criação'), ('pagamento', 'Pagamento'), ('participacao', 'Participação'), ('performance', 'Performance')], max_length=20)),
                ('pontos_recompensa', models.PositiveIntegerField(default=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(choices=[(1, 'Bronze'), (2, 'Prata'), (3, 'Ouro'), (4, 'Platina'), (5, 'Diamante')], unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('pontos_minimos', models.PositiveIntegerField(help_text='Pontos mínimos necessários para alcançar este nível')),
                ('beneficios', models.TextField(blank=True, help_text='Benefícios do nível')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuariorecompensa',
            options={'verbose_name': 'Recompensa do Usuário', 'verbose_name_plural': 'Recompensas do Usuário'},
        ),
        migrations.AddField(
            model_name='usuariorecompensa',
            name='data_desbloqueio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariorecompensa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_desbloqueadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorecompensa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usuariorecompensa',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gamification.badge'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorecompensa',
            unique_together={('usuario', 'badge')},
        ),
        migrations.CreateModel(
            name='Pontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_acumulado', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontos',
                'verbose_name_plural': 'Pontos',
            },
        ),
        migrations.RemoveField(
            model_name='usuariorecompensa',
            name='data_recompensa',
        ),
        migrations.RemoveField(
            model_name='usuariorecompensa',
            name='recompensa',
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuarios', 'Usuários'), ('artistas', 'Artistas')], max_length=20)),
                ('posicao', models.PositiveIntegerField()),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('mes', models.CharField(blank=True, help_text='YYYY-MM para rankings mensais', max_length=7)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['tipo', 'posicao'],
                'unique_together': {('tipo', 'usuario', 'mes')},
            },
        ),
    ]
