# Generated by Django 5.2.7 on 2026-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('texto', 'Texto'), ('design', 'Design'), ('combinada', 'Combinada')], default='design', max_length=20)),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='personalizacoes/')),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personalização',
                'verbose_name_plural': 'Personalizações',
                'ordering': ['nome'],
            },
        ),
    ]
