# Generated by Django 5.2.7 on 2026-01-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('creations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Personalização', 'verbose_name_plural': 'Personalizações'},
        ),
        migrations.RenameField(
            model_name='personalizacao',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='personalizacao',
            old_name='preco_adicional',
            new_name='preco_extra',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='personalizacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='fonte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='texto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Arte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('arquivo', models.ImageField(upload_to='artes/')),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artes', to='artists.artista')),
            ],
            options={
                'verbose_name': 'Arte',
                'verbose_name_plural': 'Artes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='arte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizacoes', to='creations.arte'),
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to='artists.artista')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='arte',
            name='colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to='creations.colecao'),
        ),
    ]
