# Generated by Django 5.2.7 on 2026-01-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artista_options_and_more'),
        ('creations', '0003_arte_atualizado_em_colecao_atualizado_em_and_more'),
        ('products', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveIndex(
            model_name='arte',
            name='creations_a_artista_e5fa5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='arte',
            name='creations_a_colecao_9fd27e_idx',
        ),
        migrations.RemoveIndex(
            model_name='arte',
            name='creations_a_criado__d085ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='colecao',
            name='creations_c_criado__bfcd80_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalizacao',
            name='creations_p_arte_id_aba366_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalizacao',
            name='creations_p_criado__9bd383_idx',
        ),
        migrations.AddField(
            model_name='personalizacao',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto que esta personalização se aplica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personalizacoes', to='products.produto'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='arquivo',
            field=models.ImageField(upload_to='artes/'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artes', to='artists.artista'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='arte',
            name='colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to='creations.colecao'),
        ),
        migrations.AlterField(
            model_name='arte',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arte',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to='artists.artista'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='colecoes/'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='arte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizacoes', to='creations.arte'),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='cor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='fonte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalizacao',
            name='texto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='colecao',
            index=models.Index(fields=['criado_em'], name='creations_c_criado__ff6100_idx'),
        ),
    ]
